# Generated by Django 5.2.5 on 2025-08-08 09:01

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=posts.models.edit_image_name),
        ),
    ]
